Fix WebXR referenceSpace error
This change avoids this error seen on entering AR:

DOMException: Failed to execute 'requestReferenceSpace' on 'XRSession': This device does not support the requested reference space type.